export const profile = {
	issuer: '[IssuerName]',
	sessionIndex: '[SessionIndex]',
	nameID: '[nameID]',
	displayName: '[DisplayName]',
	anotherName: '[AnotherName]',
	username: '[username]',
	anotherUsername: '[AnotherUserName]',
	roles: 'user,ruler,admin,king,president,governor,mayor',
	otherRoles: 'user,customer,client',
	language: 'ptbr',
	channels: 'pets,pics,funny,random,babies',
	multipleChannels: ['pets', 'pics', 'funny', 'random', 'babies'],
	customField1: 'value1',
	customField2: 'value2',
	customField3: 'value3',
	email: 'testing@server.com',
};
